### ISSUE TITLE
PUT/GET Limitation when file is > ~2GB 

### ISSUE THREAD

**Issue by c054864** [chadj2/oracp#1]
Hi, there appears to be a limitation when transferring files that are over > 2GB, possibly due to to using int versus long?

$ ./oracp.sh -f -u xxxxx -p xxxxxx -s DPUMP_DIR --url jdbc:oracle:thin:@//xxx.xxx.xxx:1521/step put largeFile3.txt
Opening Connection...
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
Starting task: PUT
Source: /home/stibosw/oracp-ojdbc7-1.1.0/largeFile3.txt (2145.70 MB)
Process Failed: Numeric Overflow
java.sql.SQLException: Numeric Overflow
	at oracle.jdbc.driver.NumberCommonAccessor.throwOverflow(NumberCommonAccessor.java:4170) ~[ojdbc7-12.1.0.2.jar:12.1.0.2.0]
	at oracle.jdbc.driver.NumberCommonAccessor.getInt(NumberCommonAccessor.java:119) ~[ojdbc7-12.1.0.2.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleCallableStatement.getInt(OracleCallableStatement.java:1815) ~[ojdbc7-12.1.0.2.jar:12.1.0.2.0]
	at oracle.jdbc.driver.OracleCallableStatementWrapper.getInt(OracleCallableStatementWrapper.java:780) ~[ojdbc7-12.1.0.2.jar:12.1.0.2.0]
	at org.oracp.sql.OraFile.readAttr(OraFile.java:181) ~[oracp-1.1.0.jar:1.1.0]`

Regards, 
Paul

**Comment by chadj2** [comment]
Thanks for pointing this out. It looks like The FGETATTR procedure is returning INTEGER and it should be using BIGINT. I am glad it is partially working for you and I was not sure anyone was using this.

I no longer work for Oracle or have a dev instance to do maintenance on this.  I may fix this if I can justify the effort to setup an environment.

**Comment by JoshHutchison** [comment]
For anyone interested, I got this working (only tested with GET) with the following changes:
OraFile.java:
49  private long _length =0;
84  public long length()
181 this._length = cs.getLong(3);

OraInputStream.java:
Comment the Override available() method or lines 53-58
